name: yolo-circle-detection
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - geopandas
  - fiona
  - rasterio
  - shapely
  - opencv
  - tifffile
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - ultralytics
